---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    
- name: Install Python 3
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install pip
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install boto3 using pip3
  become: true
  pip:
    name: boto3
    state: present

- name: Install AWS CLI using pip
  become: true
  pip:
    name: awscli
    state: latest
    executable: pip3

# need to update again so java can install successfully
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    
- name: Install Java JDK 17
  ansible.builtin.apt:
    name: openjdk-17-jdk 
    state: present

